version: '3'
services:
  rc-postgres:
    container_name: rc-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: redis
    ports:
      - "5432:5432"
    restart: always

  rc-redis:
    container_name: rc-redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  redis-cache:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - "rc-postgres"
      - "rc-redis"